saftely check on hostname

diff --git a/conf b/conf
--- a/conf
+++ b/conf
@@ -8,6 +8,12 @@ domain=theclarkhome.com
 version=xenial
 network=enp3s0
 
+if [[ ${host} = $(hostname) ]]
+then
+	echo "${host} cannot equal $(hostname)" >&2
+	exit 1
+fi
+
 case ${host} in
 foxtrot)
 	boot=efi
@@ -24,6 +30,8 @@ golf)
 test)
 	pool=testpool
 	disks="/test/1.img"
+	wholedisk=true
+	boot=efi
 	;;
 esac
 ls -l ${disks}
